Update config `release` and `dist` behaviour
getsentry/sentry-dart-plugin pull request #217
Opened 2024-03-26 14:42 UTC by denrase

## :scroll: Description

- Per default, the release is build from `pubspec.yaml` `name` & `version`: 'name@version'
- If a build number is present in `pubspec.yaml` `version`, it is used as `dist`
- If a `release` is present as env variable or in plugin `config`, it overrides the default release
- If a `dist` is present as env variable or in plugin `config`, it is used instead of any build number in `pubspec.yaml` `version`
- A `release` from env variable or from plugin `config` never gets `dist` appended

- Env variables `SENTRY_RELEASE` and `SENTRY_DIST` have precedence over values from plugin `config`

## :bulb: Motivation and Context

Closes #207

## :green_heart: How did you test it?

Unit tests

## :pencil: Checklist

- [ ] I reviewed submitted code
- [ ] I added tests to verify changes
- [ ] I updated the docs if needed
- [ ] All tests passing
- [ ] No breaking changes

## :crystal_ball: Next steps

2024-03-26 15:03 UTC, denrase commented
@stefanosiano Please add your 2 cents here, as this is changing current behaviour.

2024-04-09 08:05 UTC, buenaflor commented
Since this is breaking, should we consider releasing it as `2.0.0` ?

2024-04-09 08:17 UTC, buenaflor requested changes
What's missing for me is a readme update, that would be great so we can be as clear as possible on how the plugin creates releases.

Other than that it looks good to me but maybe @stefanosiano can have a quick pass on it too

2024-04-09 09:46 UTC, denrase commented
@buenaflor Added info in readme. This PR points to #216. So when we merge here we can check for 2.0 release. WDYT?

2024-04-09 10:11 UTC, buenaflor commented
@denrase sounds good

2024-04-09 10:12 UTC, buenaflor approved these changes

2024-04-09 11:55 UTC, merged